SpotifyApp/models.py
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
import uuid
from datetime import datetime
from werkzeug.security import generate_password_hash, check_password_hash
import secrets

#imports for login manager
from flask_login import UserMixin
#import for flask login
from flask_login import LoginManager
#import for flask-marshmallow
from flask_marshmallow import Marshmallow

db = SQLAlchemy()
login_manager = LoginManager()
ma = Marshmallow()
@login_manager.user_loader
def load_user(user_id):
    return User.query.get(user_id)



# make sure to add in usermixin to user class
class User(db.Model, UserMixin):
    id = db.Column(db.String, primary_key = True)
    first_name = db.Column(db.String(150), nullable = True, default = '')
    last_name = db.Column(db.String(150), nullable = True, default = '')
    email = db.Column(db.String(150), nullable = False)
    password = db.Column(db.String, nullable = True, default = '')
    g_auth_verify = db.Column(db.Boolean, default = False)
    token = db.Column(db.String, default = '', unique = True)
    date_created = db.Column(db.DateTime, nullable = False, default = datetime.utcnow)

    def __init__(self, email, first_name = '', last_name = '', id = '', password='', token='', g_auth_verify = False):
        self.id = self.set_id()
        self.first_name = first_name
        self.last_name = last_name
        self.password = self.set_password(password)
        self.email = email
        self.token = self.set_token(24)
        self.g_auth_verify = g_auth_verify

    def set_token(self, length):
        return secrets.token_hex(length)

    def set_id(self):
        return str(uuid.uuid4())

    def set_password(self, password):
        self.pw_hash = generate_password_hash(password)
        return self.pw_hash
        
    def __repr__(self):
        return f"User {self.email} has been added to the database!"


class Artist(db.Model):
    artist = db.Column(db.String, primary_key = True )
    related_artist = db.Column(db.String(150), nullable = False, default = '')
    genres = db.Column(db.String(150), nullable = False, default = '')
    images = db.Column(db.String(150), nullable = False, default = '')

    def __init__(self, data):
        self.artist = data['artist']
        self.related_artist = data['artist']['name']
        self.genres = data['artist']['genres'][0]
        self.images = data['artist']['images'][2]['url']

SpotifyApp/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField
from wtforms.validators import DataRequired, Email


class UserLoginForm(FlaskForm):
    # email password submit button
    email = StringField('Email', validators = [DataRequired(), Email()])
    password = PasswordField('Password', validators= [DataRequired()])
    submit_button = SubmitField()

class SpotifyForm(FlaskForm):
    form_artist = StringField('Artist', validators = [DataRequired()])
    submit_button = SubmitField()

SpotifyApp/__init__.py
from flask import Flask
from config import Config
from .site.routes import site
from .authentication.routes import auth
from .api.routes import api

from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate

from .models import db as root_db, login_manager, ma

#import flask marshmallow
from flask_marshmallow import Marshmallow
#import flask cors
from flask_cors import CORS


app = Flask(__name__)

app.register_blueprint(site)
app.register_blueprint(auth)
app.register_blueprint(api)

app.config.from_object(Config)

root_db.init_app(app) 

migrate = Migrate(app, root_db)

login_manager.init_app(app)
login_manager.login_view = 'auth.signin' # specify what page to load for non authenticated users

ma.init_app(app)

CORS(app)

SpotifyApp/api/routes.py
from flask import Blueprint

api = Blueprint('api', __name__, url_prefix='/api')

@api.route('/getdata')
def getdata():
    return {'some': 'value'}

SpotifyApp/authentication/routes.py
from flask import Blueprint, render_template, request, redirect, url_for, flash
from SpotifyApp.models import User, db, check_password_hash
from SpotifyApp.forms import UserLoginForm
#imports for flask_Login
from flask_login import login_user, logout_user, current_user, login_required


auth = Blueprint('auth', __name__, template_folder = 'auth_templates')

@auth.route('/signup', methods = ['GET', 'POST'])
def signup():
    form = UserLoginForm()

    try:
        if request.method == 'POST' and form.validate_on_submit():
            email = form.email.data
            password = form.password.data
            print(email, password)

            user = User(email, password = password)

            db.session.add(user)
            db.session.commit()

            flash(f'You have succesfully created a user account: {email}', 'user-created')

            return redirect(url_for('site.home'))
    except:
        raise Exception('Invalid Form Data: Please check your form')

    return render_template('signup.html', form=form)

@auth.route('/signin', methods = ['GET', 'POST'])
def signin():
    form = UserLoginForm()

    try:
        if request.method == 'POST' and form.validate_on_submit():
            email = form.email.data
            password = form.password.data
            print(email, password)

            logged_user = User.query.filter(User.email == email).first()
            if logged_user and check_password_hash(logged_user.password, password):
                login_user(logged_user)
                flash('You were succesfully logged in: Via email/password', 'auth-success')
                return redirect(url_for('site.artists'))
            else:
                flash('Your email/password is incorrect', 'auth-failed')
                return redirect(url_for('auth.signin'))
    except:
        raise Exception('Invalid Form Data: Please check your form')
    return render_template('signin.html', form=form)

@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('site.home'))

SpotifyApp/site/routes.py
from flask import Blueprint, render_template, request, flash, redirect, url_for
from flask_login.utils import login_required
# import base64
# import datetime
# from urllib.parse import urlencode
# import requests
# import os
# from dotenv import load_dotenv
from SpotifyApp.Spotify.access import spotify
from SpotifyApp.forms import SpotifyForm 
from SpotifyApp.models import Artist, db

"""
Note that in the code below,
some of the arguments are specified when creating the blueprint object
the first argument, "site", is the blueprints name
which is sed by Flasks routing mechanism

the second arg is __name__, is the blueprint import name
which flask uses to locate the blueprints resources
"""


site = Blueprint('site', __name__, template_folder='site_templates')

@site.route('/')
def home():
    return render_template('index.html')

@site.route('/profile')
@login_required
def profile():
    return render_template('profile.html')

@site.route('/artists', methods = ['GET', 'POST'])
@login_required
def artists():
    form = SpotifyForm()
    related_artists = None
    try:
        if request.method == 'POST' and form.validate_on_submit():
            form_artist = form.form_artist.data
            print(f' form artist {form_artist}')
            artist = spotify.search(query= form_artist) # 
            # print(artist['artists']['items'][0]['name'])
            id = (artist['artists']['items'][0]['id'])
            related_artists = spotify.get_resource(id)
            related_artists = related_artists['artists']
            print(f"RELATED ARTIST IMAGE {related_artists[0]['images'][2]}")
            print(f"RELATED ARTISTS NAME {related_artists[0]['name']}")
            print(f"RELATED ARTISTS GENRES {related_artists[0]['genres'][0]}")
            print(f"RELATED ARTISTS LINK {related_artists[0]['external_urls']['spotify']}")
            print(f"RELATED ARTIST ??? {related_artists[0]}")
            # for artist in related_artists:
            #     musician = Artist(artist) 
            #     db.session.add(musician)
            #     db.session.commit()

            flash(f"You have succesfully called an artist")
            redirect(url_for('site.artists'))
        else:
            flash('Cannot find artists')

    except:
        raise Exception('Invalid Form Data: Please make sure spelling is correct')
    
    return render_template('artists.html', form=form, related_artists = related_artists)

SpotifyApp/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="ie=edge">
<meta name="Description" content="Enter your description here"/>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.1.0/css/bootstrap.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
<link rel="stylesheet" href="../static/css/main.css">
<title>Spotify App</title>
</head>
<body>

    <!-- Nav bar here -->
    <nav class="ct-nav">
        <div>
            <img src="../static/images/spotify-download-logo-30.png" alt="">
        </div>
        <div>
            <ul id="horizontal-list">
                <a href="{{ url_for('site.home') }} ">
                    <li>Spotify Project</li>
                </a>
                <!-- <a href="{{ url_for('site.profile') }}">
                    <li>Profile</li>
                </a> -->
                <a href="{{ url_for('site.artists') }}">
                    <li>Related Artists</li>
                </a>
                {% if current_user.is_authenticated %}
                <a href="{{ url_for('auth.logout') }}">
                    <li>Log Out</li>
                </a>
                {% else %}
                <a href="{{ url_for('auth.signin') }}">
                    <li>Sign In</li>
                </a>
                <a href="{{ url_for('auth.signup') }}">
                    <li>Sign Up</li>
                </a>
                {% endif %}
            </ul>
        </div>
    </nav>

    {% block content %}
    {% endblock content %}
    
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.9.2/umd/popper.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.1.0/js/bootstrap.min.js"></script>
</body>
</html>

SpotifyApp/templates/forms.html
<!-- HTML produced by flask form -->

<form method = "POST">
    {{ form.hidden_tag() }}
    <div class="form-group">
        <fieldset id="email-field">
            {{ form.email.label }}
            {{ form.email(class = "form-control", placeholder="Place Email Here") }}

        </fieldset>
        <fieldset id="pass-field">
            {{ form.password.label }}
            {{ form.password( class = "form-control", placeholder="Place Password Here") }}

        </fieldset>
        <!-- Submit Button -->
        {{ form.submit_button( class = "btn btn-dark btn-block") }}
    </div>

</form>

SpotifyApp/templates/spotify_form.html
<form method = "POST">
    {{ form.hidden_tag() }}
    <div class="form-group">
        <fieldset id="artist-field">
            <!-- {{ form.form_artist.label }} -->
            {{ form.form_artist(class = "form-control", placeholder="Place Artist Here") }}

        </fieldset>

        <!-- Submit Button -->
        {{ form.submit_button( class = "btn btn-dark btn-block") }}
    </div>

</form>